//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Modules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string align {
            get {
                return ResourceManager.GetString("align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolTip.
        /// </summary>
        internal static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string bgColor {
            get {
                return ResourceManager.GetString("bgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Window.
        /// </summary>
        internal static string blank {
            get {
                return ResourceManager.GetString("blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Width.
        /// </summary>
        internal static string border {
            get {
                return ResourceManager.GetString("border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border color.
        /// </summary>
        internal static string borderColor {
            get {
                return ResourceManager.GetString("borderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellPadding.
        /// </summary>
        internal static string cellPadding {
            get {
                return ResourceManager.GetString("cellPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellSpacing.
        /// </summary>
        internal static string cellSpacing {
            get {
                return ResourceManager.GetString("cellSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classname.
        /// </summary>
        internal static string className {
            get {
                return ResourceManager.GetString("className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string cols {
            get {
                return ResourceManager.GetString("cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Doctype.
        /// </summary>
        internal static string Doctype {
            get {
                return ResourceManager.GetString("Doctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveElement.
        /// </summary>
        internal static string DomInspectorRemoveElement {
            get {
                return ResourceManager.GetString("DomInspectorRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Report Pane.
        /// </summary>
        internal static string ExpandValidator {
            get {
                return ResourceManager.GetString("ExpandValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string href {
            get {
                return ResourceManager.GetString("href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media Pane.
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value. Please enter a number..
        /// </summary>
        internal static string NodeInspectorInvalidValue {
            get {
                return ResourceManager.GetString("NodeInspectorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected element is .
        /// </summary>
        internal static string NodeInspectorSelectedElement {
            get {
                return ResourceManager.GetString("NodeInspectorSelectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowrap.
        /// </summary>
        internal static string noWrap {
            get {
                return ResourceManager.GetString("noWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Window.
        /// </summary>
        internal static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Inspector.
        /// </summary>
        internal static string RadEditorDomInspector {
            get {
                return ResourceManager.GetString("RadEditorDomInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real-Time HTML View.
        /// </summary>
        internal static string RadEditorHtmlInspector {
            get {
                return ResourceManager.GetString("RadEditorHtmlInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties Inspector.
        /// </summary>
        internal static string RadEditorNodeInspector {
            get {
                return ResourceManager.GetString("RadEditorNodeInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string RadEditorStatistics {
            get {
                return ResourceManager.GetString("RadEditorStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XHTML Validator.
        /// </summary>
        internal static string RadEditorXhtmlValidator {
            get {
                return ResourceManager.GetString("RadEditorXhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string rows {
            get {
                return ResourceManager.GetString("rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Pane.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Window.
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters:.
        /// </summary>
        internal static string StatisticsCharacters {
            get {
                return ResourceManager.GetString("StatisticsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words:.
        /// </summary>
        internal static string StatisticsWords {
            get {
                return ResourceManager.GetString("StatisticsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string target {
            get {
                return ResourceManager.GetString("target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Window.
        /// </summary>
        internal static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate XHTML.
        /// </summary>
        internal static string ValidateXHTML {
            get {
                return ResourceManager.GetString("ValidateXHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Alignment.
        /// </summary>
        internal static string vAlign {
            get {
                return ResourceManager.GetString("vAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
