//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Custom Color....
        /// </summary>
        internal static string AddCustomColor {
            get {
                return ResourceManager.GetString("AddCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Hex Color....
        /// </summary>
        internal static string AddCustomHexColor {
            get {
                return ResourceManager.GetString("AddCustomHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successfully added to dictionary.
        /// </summary>
        internal static string AddCustomWordSuccess {
            get {
                return ResourceManager.GetString("AddCustomWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to dictionary.
        /// </summary>
        internal static string AddToDictionary {
            get {
                return ResourceManager.GetString("AddToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content you are trying to paste has MS Word formatting.
        ///Would you like to clean it?.
        /// </summary>
        internal static string AskWordCleaning {
            get {
                return ResourceManager.GetString("AskWordCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelTable {
            get {
                return ResourceManager.GetString("CancelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Properties.
        /// </summary>
        internal static string CellProperties {
            get {
                return ResourceManager.GetString("CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a cell to set its properties!.
        /// </summary>
        internal static string CellWarning {
            get {
                return ResourceManager.GetString("CellWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Manually.
        /// </summary>
        internal static string ChangeWordString {
            get {
                return ResourceManager.GetString("ChangeWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All HTML Tags.
        /// </summary>
        internal static string ClearAllHtmlTags {
            get {
                return ResourceManager.GetString("ClearAllHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Class.
        /// </summary>
        internal static string ClearClass {
            get {
                return ResourceManager.GetString("ClearClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cascading Style Sheets.
        /// </summary>
        internal static string ClearCssFormatting {
            get {
                return ResourceManager.GetString("ClearCssFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Tags.
        /// </summary>
        internal static string ClearFontTags {
            get {
                return ResourceManager.GetString("ClearFontTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Formatting.
        /// </summary>
        internal static string ClearFormatting {
            get {
                return ResourceManager.GetString("ClearFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span Tags.
        /// </summary>
        internal static string ClearSpanTags {
            get {
                return ResourceManager.GetString("ClearSpanTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Style.
        /// </summary>
        internal static string ClearStyle {
            get {
                return ResourceManager.GetString("ClearStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Word Formatting.
        /// </summary>
        internal static string ClearWordFormatting {
            get {
                return ResourceManager.GetString("ClearWordFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Changes.
        /// </summary>
        internal static string CorrectSpelling {
            get {
                return ResourceManager.GetString("CorrectSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Link.
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialogs.
        /// </summary>
        internal static string DialogToolbar {
            get {
                return ResourceManager.GetString("DialogToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdowns.
        /// </summary>
        internal static string DropdownToolbar {
            get {
                return ResourceManager.GetString("DropdownToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Edit.
        /// </summary>
        internal static string EnhancedEditToolbar {
            get {
                return ResourceManager.GetString("EnhancedEditToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The added HTML code exceeded the character limit.
        /// </summary>
        internal static string ExceededHtmlLength {
            get {
                return ResourceManager.GetString("ExceededHtmlLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The added text exceeded the character limit.
        /// </summary>
        internal static string ExceededTextLength {
            get {
                return ResourceManager.GetString("ExceededTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open file...
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string FileSaveAs {
            get {
                return ResourceManager.GetString("FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button.
        /// </summary>
        internal static string FormButton {
            get {
                return ResourceManager.GetString("FormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkbox.
        /// </summary>
        internal static string FormCheckbox {
            get {
                return ResourceManager.GetString("FormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Form elements are only supported when the content area is set to Iframe!.
        /// </summary>
        internal static string FormElementsAreSupportedByIframeError {
            get {
                return ResourceManager.GetString("FormElementsAreSupportedByIframeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form.
        /// </summary>
        internal static string FormForm {
            get {
                return ResourceManager.GetString("FormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden.
        /// </summary>
        internal static string FormHidden {
            get {
                return ResourceManager.GetString("FormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio button.
        /// </summary>
        internal static string FormRadio {
            get {
                return ResourceManager.GetString("FormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string FormReset {
            get {
                return ResourceManager.GetString("FormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string FormSelect {
            get {
                return ResourceManager.GetString("FormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textarea.
        /// </summary>
        internal static string FormTextarea {
            get {
                return ResourceManager.GetString("FormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadEditor._getAllSheets called with no document object provided!.
        /// </summary>
        internal static string GetAllSheetsCalledWithNoDocumentError {
            get {
                return ResourceManager.GetString("GetAllSheetsCalledWithNoDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Mode.
        /// </summary>
        internal static string HtmlMode {
            get {
                return ResourceManager.GetString("HtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore All.
        /// </summary>
        internal static string IgnoreAllString {
            get {
                return ResourceManager.GetString("IgnoreAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string IgnoreString {
            get {
                return ResourceManager.GetString("IgnoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select an image to set its image map properties!.
        /// </summary>
        internal static string ImageMapWarning {
            get {
                return ResourceManager.GetString("ImageMapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent HTML.
        /// </summary>
        internal static string IndentHtml {
            get {
                return ResourceManager.GetString("IndentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string InsertToolbar {
            get {
                return ResourceManager.GetString("InsertToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Toolbar.
        /// </summary>
        internal static string MainToolbar {
            get {
                return ResourceManager.GetString("MainToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This word occurs more than once in the text. Would you like to replace all instances?.
        /// </summary>
        internal static string MoreThanOnceMessage {
            get {
                return ResourceManager.GetString("MoreThanOnceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mistakes found..
        /// </summary>
        internal static string NoSpellingMistakes {
            get {
                return ResourceManager.GetString("NoSpellingMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no suggestions).
        /// </summary>
        internal static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, provide the custom color HEX value:.
        /// </summary>
        internal static string PromptColor {
            get {
                return ResourceManager.GetString("PromptColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string RadEditorDesignMode {
            get {
                return ResourceManager.GetString("RadEditorDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content....
        /// </summary>
        internal static string RadEditorGroupboxContent {
            get {
                return ResourceManager.GetString("RadEditorGroupboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string RadEditorGroupboxTitle {
            get {
                return ResourceManager.GetString("RadEditorGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string RadEditorHtmlMode {
            get {
                return ResourceManager.GetString("RadEditorHtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string RadEditorPreviewMode {
            get {
                return ResourceManager.GetString("RadEditorPreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, reduce the content of the field.
        /// </summary>
        internal static string ReduceTheConentLength {
            get {
                return ResourceManager.GetString("ReduceTheConentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize Object.
        /// </summary>
        internal static string ResizeCommand {
            get {
                return ResourceManager.GetString("ResizeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set HTML.
        /// </summary>
        internal static string SetHtml {
            get {
                return ResourceManager.GetString("SetHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Set EditorContentAreaMode to Iframe if you want to edit full page HTML!.
        /// </summary>
        internal static string SetToIframeForFullHTMLError {
            get {
                return ResourceManager.GetString("SetToIframeForFullHTMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show toolbar.
        /// </summary>
        internal static string ShowToolbarTooltip {
            get {
                return ResourceManager.GetString("ShowToolbarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Spell Check is complete!.
        /// </summary>
        internal static string SpellCheckComplete {
            get {
                return ResourceManager.GetString("SpellCheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish spellchecking.
        /// </summary>
        internal static string SpellCheckEnd {
            get {
                return ResourceManager.GetString("SpellCheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling Change.
        /// </summary>
        internal static string SpellingChange {
            get {
                return ResourceManager.GetString("SpellingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell checking in progress....
        /// </summary>
        internal static string SpellingInProgress {
            get {
                return ResourceManager.GetString("SpellingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell checking mode. Misspelled words are highlighted in yellow..
        /// </summary>
        internal static string SpellingMode {
            get {
                return ResourceManager.GetString("SpellingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TableToolbar {
            get {
                return ResourceManager.GetString("TableToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select a table to set its properties!.
        /// </summary>
        internal static string TableWarning {
            get {
                return ResourceManager.GetString("TableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RadEditor Toolbar.
        /// </summary>
        internal static string ToolbarCaption {
            get {
                return ResourceManager.GetString("ToolbarCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool is not supported by Mozilla/Netscape browsers..
        /// </summary>
        internal static string ToolNotSupportedByNetscape {
            get {
                return ResourceManager.GetString("ToolNotSupportedByNetscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typing....
        /// </summary>
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot undo further while in spellcheck mode. Please finish spellchecking first..
        /// </summary>
        internal static string UndoDisabledMessage {
            get {
                return ResourceManager.GetString("UndoDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use Ctrl+C to Copy (Cmd+C on Mac).
        /// </summary>
        internal static string UseCtrlC {
            get {
                return ResourceManager.GetString("UseCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use Ctrl+V to Paste (Cmd+V on Mac).
        /// </summary>
        internal static string UseCtrlV {
            get {
                return ResourceManager.GetString("UseCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use Ctrl+X to Cut (Cmd+X on Mac).
        /// </summary>
        internal static string UseCtrlX {
            get {
                return ResourceManager.GetString("UseCtrlX", resourceCulture);
            }
        }
    }
}
