//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadGrid {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadGrid.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AddNewRecordImageUrl {
            get {
                return ResourceManager.GetString("AddNewRecordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new record.
        /// </summary>
        internal static string AddNewRecordText {
            get {
                return ResourceManager.GetString("AddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        internal static string AggregateFunctionAvg {
            get {
                return ResourceManager.GetString("AggregateFunctionAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string AggregateFunctionCount {
            get {
                return ResourceManager.GetString("AggregateFunctionCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountDistinct.
        /// </summary>
        internal static string AggregateFunctionCountDistinct {
            get {
                return ResourceManager.GetString("AggregateFunctionCountDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string AggregateFunctionCustom {
            get {
                return ResourceManager.GetString("AggregateFunctionCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string AggregateFunctionFirst {
            get {
                return ResourceManager.GetString("AggregateFunctionFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string AggregateFunctionLast {
            get {
                return ResourceManager.GetString("AggregateFunctionLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string AggregateFunctionMax {
            get {
                return ResourceManager.GetString("AggregateFunctionMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string AggregateFunctionMin {
            get {
                return ResourceManager.GetString("AggregateFunctionMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string AggregateFunctionSum {
            get {
                return ResourceManager.GetString("AggregateFunctionSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        internal static string BetweenText {
            get {
                return ResourceManager.GetString("BetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel changes.
        /// </summary>
        internal static string CancelChangesText {
            get {
                return ResourceManager.GetString("CancelChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Page Size.
        /// </summary>
        internal static string ChangePageSizeButtonToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePageSizeComboBoxTableSummary {
            get {
                return ResourceManager.GetString("ChangePageSizeComboBoxTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePageSizeComboBoxToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size:.
        /// </summary>
        internal static string ChangePageSizeLabelText {
            get {
                return ResourceManager.GetString("ChangePageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ChangePageSizeLinkButtonText {
            get {
                return ResourceManager.GetString("ChangePageSizeLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ChangePageSizeTextBoxToolTip {
            get {
                return ResourceManager.GetString("ChangePageSizeTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse group.
        /// </summary>
        internal static string CollapseTooltip {
            get {
                return ResourceManager.GetString("CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width: &lt;strong&gt;{0}&lt;/strong&gt; &lt;em&gt;pixels&lt;/em&gt;.
        /// </summary>
        internal static string ColumnResizeTooltipFormatString {
            get {
                return ResourceManager.GetString("ColumnResizeTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoesNotContain.
        /// </summary>
        internal static string DoesNotContainText {
            get {
                return ResourceManager.GetString("DoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to group or reorder.
        /// </summary>
        internal static string DragToGroupOrReorder {
            get {
                return ResourceManager.GetString("DragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to resize.
        /// </summary>
        internal static string DragToResize {
            get {
                return ResourceManager.GetString("DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop here to reorder.
        /// </summary>
        internal static string DropHereToReorder {
            get {
                return ResourceManager.GetString("DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndsWith.
        /// </summary>
        internal static string EndsWithText {
            get {
                return ResourceManager.GetString("EndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EqualTo.
        /// </summary>
        internal static string EqualToText {
            get {
                return ResourceManager.GetString("EqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand group.
        /// </summary>
        internal static string ExpandTooltip {
            get {
                return ResourceManager.GetString("ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportToCsvImageUrl {
            get {
                return ResourceManager.GetString("ExportToCsvImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to CSV.
        /// </summary>
        internal static string ExportToCsvText {
            get {
                return ResourceManager.GetString("ExportToCsvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportToExcelImageUrl {
            get {
                return ResourceManager.GetString("ExportToExcelImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcelText {
            get {
                return ResourceManager.GetString("ExportToExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportToPdfImageUrl {
            get {
                return ResourceManager.GetString("ExportToPdfImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        internal static string ExportToPdfText {
            get {
                return ResourceManager.GetString("ExportToPdfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ExportToWordImageUrl {
            get {
                return ResourceManager.GetString("ExportToWordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Word.
        /// </summary>
        internal static string ExportToWordText {
            get {
                return ResourceManager.GetString("ExportToWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FilterExpression {
            get {
                return ResourceManager.GetString("FilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string FilterImageToolTip {
            get {
                return ResourceManager.GetString("FilterImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Page.
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page:.
        /// </summary>
        internal static string GoToPageLabelText {
            get {
                return ResourceManager.GetString("GoToPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        internal static string GoToPageLinkButtonText {
            get {
                return ResourceManager.GetString("GoToPageLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string GoToPageTextBoxToolTip {
            get {
                return ResourceManager.GetString("GoToPageTextBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThanOrEqualTo.
        /// </summary>
        internal static string GreaterThanOrEqualToText {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GreaterThan.
        /// </summary>
        internal static string GreaterThanText {
            get {
                return ResourceManager.GetString("GreaterThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ; .
        /// </summary>
        internal static string GroupByFieldsSeparator {
            get {
                return ResourceManager.GetString("GroupByFieldsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ... group continued from the previous page. .
        /// </summary>
        internal static string GroupContinuedFormatString {
            get {
                return ResourceManager.GetString("GroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Group continues on the next page..
        /// </summary>
        internal static string GroupContinuesFormatString {
            get {
                return ResourceManager.GetString("GroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag a column header and drop it here to group by that column.
        /// </summary>
        internal static string GroupPanelText {
            get {
                return ResourceManager.GetString("GroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing {0} of {1} items..
        /// </summary>
        internal static string GroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("GroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0}).
        /// </summary>
        internal static string GroupSplitFormat {
            get {
                return ResourceManager.GetString("GroupSplitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aggregates.
        /// </summary>
        internal static string HeaderContextMenuAggregates {
            get {
                return ResourceManager.GetString("HeaderContextMenuAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        internal static string HeaderContextMenuAndLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuAndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        internal static string HeaderContextMenuAvgAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuAvgAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Fit.
        /// </summary>
        internal static string HeaderContextMenuBestFitText {
            get {
                return ResourceManager.GetString("HeaderContextMenuBestFitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filter.
        /// </summary>
        internal static string HeaderContextMenuClearButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string HeaderContextMenuColumns {
            get {
                return ResourceManager.GetString("HeaderContextMenuColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        internal static string HeaderContextMenuCountAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountDistinct.
        /// </summary>
        internal static string HeaderContextMenuCountDistinctAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountDistinctAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string HeaderContextMenuCustomAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCustomAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string HeaderContextMenuFilterButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string HeaderContextMenuFilterItemText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        internal static string HeaderContextMenuFirstAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFirstAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze.
        /// </summary>
        internal static string HeaderContextMenuFreeze {
            get {
                return ResourceManager.GetString("HeaderContextMenuFreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group By.
        /// </summary>
        internal static string HeaderContextMenuGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string HeaderContextMenuLastAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuLastAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        internal static string HeaderContextMenuMaxAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMaxAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        internal static string HeaderContextMenuMinAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMinAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string HeaderContextMenuNoneAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuNoneAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show rows with value that.
        /// </summary>
        internal static string HeaderContextMenuRowsLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending.
        /// </summary>
        internal static string HeaderContextMenuSortAsc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sorting.
        /// </summary>
        internal static string HeaderContextMenuSortClear {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending.
        /// </summary>
        internal static string HeaderContextMenuSortDesc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        internal static string HeaderContextMenuSumAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuSumAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfreeze.
        /// </summary>
        internal static string HeaderContextMenuUnfreeze {
            get {
                return ResourceManager.GetString("HeaderContextMenuUnfreeze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        internal static string HeaderContextMenuUnGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuUnGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string HierarchyCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchyCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string HierarchyExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchyExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self reference collapse.
        /// </summary>
        internal static string HierarchySelfCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self reference expand.
        /// </summary>
        internal static string HierarchySelfExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEmpty.
        /// </summary>
        internal static string IsEmptyText {
            get {
                return ResourceManager.GetString("IsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsNull.
        /// </summary>
        internal static string IsNullText {
            get {
                return ResourceManager.GetString("IsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Page.
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThanOrEqualTo.
        /// </summary>
        internal static string LessThanOrEqualToText {
            get {
                return ResourceManager.GetString("LessThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LessThan.
        /// </summary>
        internal static string LessThanText {
            get {
                return ResourceManager.GetString("LessThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Columns and Drag the Icon to Reorder.
        /// </summary>
        internal static string MobileColumnsViewDescription {
            get {
                return ResourceManager.GetString("MobileColumnsViewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns Display.
        /// </summary>
        internal static string MobileColumnsViewTitle {
            get {
                return ResourceManager.GetString("MobileColumnsViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MobileEditViewTitle {
            get {
                return ResourceManager.GetString("MobileEditViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string MobileFilterViewOptionsText {
            get {
                return ResourceManager.GetString("MobileFilterViewOptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by {0}.
        /// </summary>
        internal static string MobileFilterViewTitleFormat {
            get {
                return ResourceManager.GetString("MobileFilterViewTitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string MobileFilterViewValueText {
            get {
                return ResourceManager.GetString("MobileFilterViewValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string MobileInsertViewTitle {
            get {
                return ResourceManager.GetString("MobileInsertViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string MobileViewBackButtonText {
            get {
                return ResourceManager.GetString("MobileViewBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MobileViewCancelButtonText {
            get {
                return ResourceManager.GetString("MobileViewCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string MobileViewDoneButtonText {
            get {
                return ResourceManager.GetString("MobileViewDoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Groups.
        /// </summary>
        internal static string MobileViewGroupsText {
            get {
                return ResourceManager.GetString("MobileViewGroupsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextFrozenColumnText {
            get {
                return ResourceManager.GetString("NextFrozenColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Pages.
        /// </summary>
        internal static string NextPagesToolTip {
            get {
                return ResourceManager.GetString("NextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No child records to display..
        /// </summary>
        internal static string NoDetailRecordsText {
            get {
                return ResourceManager.GetString("NoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoFilter.
        /// </summary>
        internal static string NoFilterText {
            get {
                return ResourceManager.GetString("NoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records to display..
        /// </summary>
        internal static string NoMasterRecordsText {
            get {
                return ResourceManager.GetString("NoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotBetween.
        /// </summary>
        internal static string NotBetweenText {
            get {
                return ResourceManager.GetString("NotBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotEqualTo.
        /// </summary>
        internal static string NotEqualToText {
            get {
                return ResourceManager.GetString("NotEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotIsEmpty.
        /// </summary>
        internal static string NotIsEmptyText {
            get {
                return ResourceManager.GetString("NotIsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotIsNull.
        /// </summary>
        internal static string NotIsNullText {
            get {
                return ResourceManager.GetString("NotIsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of {0}.
        /// </summary>
        internal static string PageOfLabelText {
            get {
                return ResourceManager.GetString("PageOfLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change page: {4} &amp;nbsp;Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt;, items &lt;strong&gt;{2}&lt;/strong&gt; to &lt;strong&gt;{3}&lt;/strong&gt; of &lt;strong&gt;{5}&lt;/strong&gt;..
        /// </summary>
        internal static string PagerTextFormat {
            get {
                return ResourceManager.GetString("PagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt;.
        /// </summary>
        internal static string PagerTooltipFormatString {
            get {
                return ResourceManager.GetString("PagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size:.
        /// </summary>
        internal static string PageSizeLabelText {
            get {
                return ResourceManager.GetString("PageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        internal static string PrevFrozenColumnText {
            get {
                return ResourceManager.GetString("PrevFrozenColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Pages.
        /// </summary>
        internal static string PrevPagesToolTip {
            get {
                return ResourceManager.GetString("PrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        internal static string PrevPageToolTip {
            get {
                return ResourceManager.GetString("PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From: .
        /// </summary>
        internal static string RangeFilteringFromText {
            get {
                return ResourceManager.GetString("RangeFilteringFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To: .
        /// </summary>
        internal static string RangeFilteringToText {
            get {
                return ResourceManager.GetString("RangeFilteringToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RefreshImageUrl {
            get {
                return ResourceManager.GetString("RefreshImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not remove this key..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        internal static string SaveChangesText {
            get {
                return ResourceManager.GetString("SaveChangesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string SliderDecreaseText {
            get {
                return ResourceManager.GetString("SliderDecreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        internal static string SliderDragText {
            get {
                return ResourceManager.GetString("SliderDragText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string SliderIncreaseText {
            get {
                return ResourceManager.GetString("SliderIncreaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted asc.
        /// </summary>
        internal static string SortedAscToolTip {
            get {
                return ResourceManager.GetString("SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted desc.
        /// </summary>
        internal static string SortedDescToolTip {
            get {
                return ResourceManager.GetString("SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to sort.
        /// </summary>
        internal static string SortToolTip {
            get {
                return ResourceManager.GetString("SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartsWith.
        /// </summary>
        internal static string StartsWithText {
            get {
                return ResourceManager.GetString("StartsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        internal static string StatusReadyText {
            get {
                return ResourceManager.GetString("StatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to ungroup.
        /// </summary>
        internal static string UnGroupButtonTooltip {
            get {
                return ResourceManager.GetString("UnGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag out of the bar to ungroup.
        /// </summary>
        internal static string UnGroupTooltip {
            get {
                return ResourceManager.GetString("UnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
    }
}
