//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RadListBox {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RadListBox() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadListBox", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All to Bottom.
        /// </summary>
        internal static string AllToBottom {
            get {
                return ResourceManager.GetString("AllToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All to Left.
        /// </summary>
        internal static string AllToLeft {
            get {
                return ResourceManager.GetString("AllToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All to Right.
        /// </summary>
        internal static string AllToRight {
            get {
                return ResourceManager.GetString("AllToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All to Top.
        /// </summary>
        internal static string AllToTop {
            get {
                return ResourceManager.GetString("AllToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not remove this key..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Bottom.
        /// </summary>
        internal static string ToBottom {
            get {
                return ResourceManager.GetString("ToBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Left.
        /// </summary>
        internal static string ToLeft {
            get {
                return ResourceManager.GetString("ToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Right.
        /// </summary>
        internal static string ToRight {
            get {
                return ResourceManager.GetString("ToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Top.
        /// </summary>
        internal static string ToTop {
            get {
                return ResourceManager.GetString("ToTop", resourceCulture);
            }
        }
    }
}
